version: "3.7"
services:
    client:
        image: cryptify-client
        build:
            context: .
            dockerfile: packages/docker/client.Dockerfile
            target: development
        depends_on:
            - api
        ports:
            - "3000:19006"
        volumes:
            - /code/node_modules
            - /code/packages/client/node_modules
            - /code/packages/common/node_modules
            - ./packages/client:/code/packages/client
            - ./packages/common:/code/packages/common
            - ./tsconfig.json:/code/tsconfig.json
            - ./package.json:/code/package.json
            - ./yarn.lock:/code/yarn.lock
            - ./.eslintrc.js:/code/.eslintrc.js
            - ./.prettierrc.js:/code/.prettierrc.js
        environment:
            - NODE_ENV=${NODE_ENV:-dev}
    api:
        image: cryptify-api
        build:
            context: .
            dockerfile: packages/docker/api.Dockerfile
            target: development
        depends_on:
            - db
            - eth-edge
            - btc-edge
        ports:
            - "3001:80"
        volumes:
            - /code/node_modules
            - /code/packages/api/node_modules
            - /code/packages/common/node_modules
            - ./packages/api:/code/packages/api
            - ./packages/common:/code/packages/common
            - ./tsconfig.json:/code/tsconfig.json
            - ./package.json:/code/package.json
            - ./yarn.lock:/code/yarn.lock
            - ./.eslintrc.js:/code/.eslintrc.js
            - ./.prettierrc.js:/code/.prettierrc.js
        environment:
            - NODE_ENV=${NODE_ENV:-dev}
    eth-edge:
        image: cryptify-eth-edge
        build:
            context: .
            dockerfile: packages/docker/eth-edge.Dockerfile
            target: development
        depends_on:
            - db
        ports:
            - "3002:80"
        volumes:
            - /code/node_modules
            - /code/packages/eth-edge/node_modules
            - /code/packages/common/node_modules
            - ./packages/eth-edge:/code/packages/eth-edge
            - ./packages/common:/code/packages/common
            - ./tsconfig.json:/code/tsconfig.json
            - ./package.json:/code/package.json
            - ./yarn.lock:/code/yarn.lock
            - ./.eslintrc.js:/code/.eslintrc.js
            - ./.prettierrc.js:/code/.prettierrc.js
        environment:
            - NODE_ENV=${NODE_ENV:-dev}
    btc-edge:
        image: cryptify-btc-edge
        build:
            context: .
            dockerfile: packages/docker/btc-edge.Dockerfile
            target: development
        depends_on:
            - db
        ports:
            - "3003:80"
        volumes:
            - /code/node_modules
            - /code/packages/btc-edge/node_modules
            - /code/packages/common/node_modules
            - ./packages/btc-edge:/code/packages/btc-edge
            - ./packages/common:/code/packages/common
            - ./tsconfig.json:/code/tsconfig.json
            - ./package.json:/code/package.json
            - ./yarn.lock:/code/yarn.lock
            - ./.eslintrc.js:/code/.eslintrc.js
            - ./.prettierrc.js:/code/.prettierrc.js
        environment:
            - NODE_ENV=${NODE_ENV:-dev}
    db:
        image: cryptify-db
        build:
            context: .
            dockerfile: packages/docker/db.Dockerfile
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data/
    test-db:
        image: cryptify-test-db
        build:
            context: .
            dockerfile: packages/docker/test-db.Dockerfile
        ports:
            - "5433:5432"
volumes:
    db-data:
