version: "3.7"
services:
    client:
        image: cryptify-client
        build:
            context: .
            dockerfile: packages/docker/client.Dockerfile
            target: development
        depends_on:
            - api
        ports:
            - "3000:19006"
        volumes:
            - /code/node_modules
            - /code/packages/client/node_modules
            - /code/packages/common/node_modules
            - ./packages/client:/code/packages/client
            - ./packages/common:/code/packages/common
            - ./tsconfig.json:/code/tsconfig.json
            - ./package.json:/code/package.json
            - ./yarn.lock:/code/yarn.lock
            - ./.eslintrc.js:/code/.eslintrc.js
            - ./.prettierrc.js:/code/.prettierrc.js
    api:
        image: cryptify-api
        build:
            context: .
            dockerfile: packages/docker/api.Dockerfile
            target: development
        depends_on:
            - api-db
            - eth-edge
        ports:
            - "3001:80"
        volumes:
            - /code/node_modules
            - /code/packages/api/node_modules
            - /code/packages/common/node_modules
            - ./packages/api:/code/packages/api
            - ./packages/common:/code/packages/common
            - ./tsconfig.json:/code/tsconfig.json
            - ./package.json:/code/package.json
            - ./yarn.lock:/code/yarn.lock
            - ./.eslintrc.js:/code/.eslintrc.js
            - ./.prettierrc.js:/code/.prettierrc.js
    eth-edge:
        image: cryptify-eth-edge
        build:
            context: .
            dockerfile: packages/docker/eth-edge.Dockerfile
            target: development
        depends_on:
            - api-db
        ports:
            - "3002:80"
        volumes:
            - /code/node_modules
            - /code/packages/eth-edge/node_modules
            - /code/packages/common/node_modules
            - ./packages/eth-edge:/code/packages/eth-edge
            - ./packages/common:/code/packages/common
            - ./tsconfig.json:/code/tsconfig.json
            - ./package.json:/code/package.json
            - ./yarn.lock:/code/yarn.lock
            - ./.eslintrc.js:/code/.eslintrc.js
            - ./.prettierrc.js:/code/.prettierrc.js

    api-db:
        image: cryptify-api-db
        build:
            context: .
            dockerfile: packages/docker/api-db.Dockerfile
        ports:
            - "5432:5432"
        volumes:
            - /var/lib/postgresql/data/
