#!/bin/bash

docker-compose down > /dev/null 2>&1

docker-compose up -d test-db
NODE_ENV=test docker-compose up -d api

#TODO seed db

if [[ "$2" = "build" ]] && [[ "$1" = "android" ]]; then
  yarn workspace @cryptify/client detox:android:release:build
elif [[ "$2" = "build" ]] && [[ "$1" = "ios" ]]; then
  yarn workspace @cryptify/client detox:ios:release:build
fi

if [[ "$1" = "android" ]]; then
  yarn workspace @cryptify/client detox:android:release:test
elif [[ "$1" = "ios" ]]; then
  yarn workspace @cryptify/client detox:ios:release:test
fi

docker-compose down > /dev/null 2>&1
