name: System Tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: macos-12
        timeout-minutes: 30
        
        env:
            DEVELOPER_DIR: /Applications/Xcode_14.0.1.app
        
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              
            - name: Node
              uses: actions/setup-node@v3

            - name: Install Dependencies
              run: yarn install

            - name: Cache Pods
              uses: actions/cache@v1
              id: podcache
              with:
                  path: ios/Pods
                  key: pods-${{ hashFiles('**/Podfile.lock') }}

            - name: Update Pods
              run: |
                  gem update cocoapods xcodeproj
                  cd ./packages/client/ios && pod install && cd ../../..
            - run: brew tap wix/brew
            - run: brew install applesimutils
            - run: brew install xcbeautify 
            - run: ./system-test ios
#            - run: yarn detox build e2e --configuration ios.sim.release
#            - run: yarn detox test e2e --configuration ios.sim.release --cleanup --debug-synchronization 200